import type { EnemyArchetype } from '@/game/core/enemies/EnemyArchetype';

export const enemyArchetypes = {
  grunt: {
    id: 'grunt',
    name: 'Grunt',
    baseStats: {
      hp: 220,
      hurtDurationMs: 240,
      hurtFlashDurationMs: 140,
      mass: 0.8,
    },
    moveSpeed: 120,
    radius: 18,
    aggroRange: 380,
    attackDefinitions: [
      {
        id: 'claw',
        config: {
          type: 'melee',
          damageType: 'physical',
          damage: 15,
          range: 42,
          windupMs: 180,
          activeMs: 80,
          recoveryMs: 190,
          cooldownMs: 850,
          moveSpeedMultiplier: 0,
          radius: 12,
          knockback: 150,
          hitStopMs: 35,
        },
      },
    ],
    lootTableId: null,
    aiProfile: {
      kind: 'melee_chase',
      aggroRange: 280,
      attackRangeBuffer: 6,
    },
    animationProfile: 'enemy_grunt',
  },
  brute: {
    id: 'brute',
    name: 'Brute',
    baseStats: {
      hp: 420,
      hurtDurationMs: 300,
      hurtFlashDurationMs: 150,
      mass: 1.8,
    },
    moveSpeed: 80,
    radius: 24,
    aggroRange: 260,
    attackDefinitions: [
      {
        id: 'slam',
        config: {
          type: 'melee',
          damageType: 'physical',
          damage: 35,
          range: 52,
          windupMs: 320,
          activeMs: 100,
          recoveryMs: 260,
          cooldownMs: 1200,
          moveSpeedMultiplier: 0,
          radius: 18,
          knockback: 260,
          hitStopMs: 70,
          cameraShakeMs: 90,
          cameraShakeIntensity: 0.0045,
        },
      },
    ],
    lootTableId: 'brute_basic',
    aiProfile: {
      kind: 'brute',
      aggroRange: 260,
      attackRangeBuffer: 8,
    },
    animationProfile: 'enemy_brute',
  },
  runner: {
    id: 'runner',
    name: 'Runner',
    baseStats: {
      hp: 120,
      hurtDurationMs: 140,
      hurtFlashDurationMs: 110,
      mass: 0.55,
    },
    moveSpeed: 190,
    radius: 16,
    aggroRange: 340,
    attackDefinitions: [
      {
        id: 'quick_slash',
        config: {
          type: 'melee',
          damageType: 'physical',
          damage: 10,
          range: 34,
          windupMs: 90,
          activeMs: 70,
          recoveryMs: 110,
          cooldownMs: 450,
          moveSpeedMultiplier: 0.35,
          radius: 10,
          knockback: 110,
          hitStopMs: 20,
        },
      },
    ],
    lootTableId: 'runner_basic',
    aiProfile: {
      kind: 'runner',
      aggroRange: 340,
      attackRangeBuffer: 4,
    },
    animationProfile: 'enemy_runner',
  },
  ranged: {
    id: 'ranged',
    name: 'Ranged',
    baseStats: {
      hp: 90,
      hurtDurationMs: 160,
      hurtFlashDurationMs: 120,
      mass: 0.65,
    },
    moveSpeed: 110,
    radius: 17,
    aggroRange: 420,
    attackDefinitions: [
      {
        id: 'bolt_stub',
        config: {
          type: 'melee',
          damageType: 'physical',
          damage: 12,
          range: 48,
          windupMs: 220,
          activeMs: 60,
          recoveryMs: 180,
          cooldownMs: 900,
          moveSpeedMultiplier: 0,
          radius: 10,
          knockback: 80,
          hitStopMs: 18,
        },
      },
    ],
    lootTableId: 'ranged_basic',
    aiProfile: {
      kind: 'ranged',
      aggroRange: 420,
      preferredRange: 240,
      projectileId: 'enemy_bolt',
    },
    animationProfile: 'enemy_ranged',
  },
} satisfies Record<string, EnemyArchetype>;

export type EnemyArchetypeId = keyof typeof enemyArchetypes;
